version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
     
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  mongo:
    image: mongo:latest
    command: mongod --quiet
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: